backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: 'public/img'
public_folder: '/img'

#Add i18n configuration----------
i18n:
  structure: multiple_folders
  locales: [it, en]
  default_locale: it
#Add i18n configuration----------


collections:
  - name: 'artworks'
    label: 'Artworks'
    folder: 'content/artworks'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    #Add i18n configuration----------
    i18n: true
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        #Add i18n configuration----------
        i18n: duplicate

      - label: 'Subtitle'
        name: 'subtitle'
        widget: 'string'
        required: false
        #Add i18n configuration----------
        i18n: duplicate

      - label: 'Begin Year'
        name: 'beginyear'
        widget: 'number'
        #Add i18n configuration----------
        i18n: duplicate

      - label: 'End Year'
        name: 'endyear'
        widget: 'number'
        #Add i18n configuration----------
        i18n: duplicate

      - label: 'Category'
        name: 'category'
        widget: 'select'
        options: ['Photo', 'Video', 'Other']
        #Add i18n configuration----------
        i18n: duplicate
      
      - label: 'Images'
        name: 'images'
        widget: 'list'
        required: false
        summary: '{{fields.image}} - {{fields.caption}}'
        #Add i18n configuration----------
        i18n: true
        fields:
          - label: 'Image'
            name: 'image'
            widget: 'image'
          - label: 'Caption'
            name: 'caption'
            widget: 'string'
            hint: 'Image caption'
            required: false

      - label: 'Video'
        name: 'video'
        widget: 'file'
        required: false
        #Add i18n configuration----------
        i18n: duplicate

      - label: 'Text'
        name: 'bodytext'
        widget: 'markdown'
        #Add i18n configuration----------
        i18n: true



  - name: 'books'
    label: 'Books'
    folder: 'content/books'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    #Add i18n configuration----------
    i18n: true
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        #Add i18n configuration----------
        i18n: duplicate

      - label: 'Subtitle'
        name: 'subtitle'
        widget: 'string'
        required: false
        #Add i18n configuration----------
        i18n: duplicate

      - label: 'Year'
        name: 'year'
        widget: 'number'
        #Add i18n configuration----------
        i18n: duplicate

      - label: 'Cover'
        name: 'cover'
        widget: 'image'
        #Add i18n configuration----------
        i18n: duplicate

      - label: 'Description'
        name: 'description'
        widget: 'markdown'
        buttons: ['bold', 'italic', 'link']
        #Add i18n configuration----------
        i18n: true

      - label: 'Order'
        name: 'order'
        widget: 'select'
        options: ['Mail', 'Website', 'No']
        #Add i18n configuration----------
        i18n: duplicate

      - label: 'Address'
        name: 'address'
        widget: 'string'
        #Add i18n configuration----------
        i18n: duplicate




  - name: 'bio'
    label: 'Bio'
    #Add i18n configuration----------
    i18n:
      structure: single_file
      locales: [it, en]
    files:
      - label: 'Biography'
        name: 'biography'
        file: 'content/bio/biography.yml'
        i18n: true
        fields:
          - label: 'Image'
            name: 'image'
            widget: 'image'
            i18n: dublicate
          - label: 'Text'
            name: 'text'
            widget: 'markdown'
            buttons: ['bold', 'italic', 'link']
            i18n: true

      - label: 'Awards'
        name: 'awards'
        file: 'content/bio/awards.yml'
        i18n: true
        fields:          
          - label: 'Award'
            name: 'award'
            widget: 'list'
            required: false
            summary: '{{fields.year}} - {{fields.text}}'
            i18n: true
            fields:
              - label: 'Year'
                name: 'year'
                widget: 'number'
              - label: 'Text'
                name: 'text'
                widget: 'markdown'
                buttons: ['bold', 'italic', 'link']

